services:
  inmind-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inmind-container-compose
    ports:
      - '4200:80'
    networks:
      - inmind-network-compose
    restart: unless-stopped

networks:
  inmind-network-compose:
    driver: bridge
